### ISSUE TITLE
Unsupported DB version (23)

### ISSUE THREAD

**Issue by sequc82** [bepaald/signalbackup-tools#230]
Hi @bepaald,

Once again, thanks for your hard work on this!

I've come across some trouble though. I have some backups from older Signal versions, which are not corrupted; I can listthreads without issue. But on export, I get the unsupported db version error. When attempting to migrate using `--migratedb`, I get the error, `[Error]: Failed to migrate currently unsupported database version (23). Please upgrade your database`

Logs:
```
$ ./signalbackup-tools [input] [passphrase] --exporthtml [DIRECTORY]
 *** Starting log: 2024-08-09 14:23:32 *** 
signalbackup-tools (./signalbackup-tools) source version 20240724.154028
BACKUPFILE VERSION: 0
BACKUPFILE SIZE: 639005016
COUNTER: 3591904966
Reading backup file: 100.0%...
Read entire backup file...
Reading backup file: 100.0%... done!
Database version: 23
[Error]: Currently unsupported database version (23).
         Please upgrade your database or append the `--migratedb' option to attempt to
         migrate this database to a supported version.
```

```
$ ./signalbackup-tools  [input] [passphrase] --exporthtml [DIRECTORY] --migratedb
 *** Starting log: 2024-08-09 14:05:10 *** 
signalbackup-tools (./signalbackup-tools) source version 20240724.154028
BACKUPFILE VERSION: 0
BACKUPFILE SIZE: 639005016
COUNTER: 3591904966
Reading backup file: 100.0%...
Read entire backup file...
Reading backup file: 100.0%... done!
Database version: 23
Attempting to migrate database from version 23 to version 170...
[Error]: During sqlite3_prepare_v2(): no such column: reactions
         -> Query: "SELECT _id, reactions FROM sms WHERE reactions IS NOT NULL"
[Error]: During sqlite3_prepare_v2(): near "DROP": syntax error
         -> Query: "ALTER TABLE sms DROP COLUMN reactions"
[Error]: During sqlite3_prepare_v2(): no such column: reactions
         -> Query: "SELECT _id, reactions FROM mms WHERE reactions IS NOT NULL"
[Error]: During sqlite3_prepare_v2(): near "DROP": syntax error
         -> Query: "ALTER TABLE mms DROP COLUMN reactions"
[Error]: During sqlite3_prepare_v2(): no such table: recipient
         -> Query: "ALTER TABLE recipient ADD COLUMN wallpaper BLOB DEFAULT NULL"
[Error]: Failed to migrate currently unsupported database version (23). Please upgrade your database
```

I know from the closed issues here, there's been a number of DB design changes causing a lot of trouble.  Is there something I'm missing here?

**Comment by bepaald** [comment]
>I know from the closed issues here, there's been a number of DB design changes causing a lot of trouble. Is there something I'm missing here?

You are not missing anything, the database version was simply too old to be supported. I had a go at this today, but between versions 23 to 24 were some huge changes in the database so I'm not sure how well it works. Please try the current version and let me know of any errors/warnings you see in the output.

Thanks!

**Comment by bepaald** [comment]
I believe this issue is solved. Let me know if you think otherwise, it can always be reopened. Thanks!

**Comment by sequc82** [comment]
Hi @bepaald,

Thanks for the replies, sorry I didn't see them sooner!

I just pulled the most recent changes to signalbackup-tools, but I still get the same errors. It sounds like you have had luck using DB version 23, is there something I'm missing in the command syntax to make it work? Or do I need to upgrade the DB from version 23? 

If so, how might I do that? Would it have to be done via an upgrade of the Signal app on the device?

Thanks again!

**Comment by bepaald** [comment]
Are you sure you are running the latest version? Could you show me the output? There could of course be bugs, but it would surprise me if you got the exact same errors as before.

When I run it on a v23 backup I get:
```
$ signalbackup-tools /mnt/1TDATA/old_signal_backups/signal-2019-10-17-11-42-09.backup [passphrase] --exporthtml DBV23_HTML --migratedb
 *** Starting log: 2024-09-02 20:51:14 *** 
signalbackup-tools (signalbackup-tools) source version 20240830.161358
BACKUPFILE VERSION: 0
BACKUPFILE SIZE: 2441682956
COUNTER: 720853041
Reading backup file: 100.0%...
Read entire backup file...
Reading backup file: 100.0%... done!
Database version: 23
Attempting to migrate database from version 23 to version 170...
Dealing with thread 1
Dealing with thread 2
Dealing with thread 3
Dealing with thread 4
Dealing with thread 5
Dealing with thread 6
[...]
```

Note the `source version 20240830.161358`, and that I did add `--migratedb`. If you do stilll get the exact same errors, I will need to add some extra output during the migration attempt to see where it fails.

Thanks!

**Comment by bepaald** [comment]
>First, thanks for all your support. While I had pulled the most recent updates, I was dumb and forgot to build a new binary; sleeping helped with that one, haha

😀

>[Error]: During sqlite3_prepare_v2(): near "RETURNING": syntax error

Hm, what's your sqlite version? Any chance it's a version before 3.35.0?

**Comment by sequc82** [comment]
Hi @bepaald 

Good call; it looks like I'm runing sqlite 3.34.1. I figured I'd check for an update, but it doesn't look like it's hit RHEL9 appstream yet. 

I'd be happy to test for you! What do you need from me?

**Comment by bepaald** [comment]
I have a small patch for this, I can not attach it to this message for some reason, so I'll just paste the contents here:
```Diff
diff --git a/signalbackup/migratedatabase.cc b/signalbackup/migratedatabase.cc
index 16b199d..b8b736e 100644
--- a/signalbackup/migratedatabase.cc
+++ b/signalbackup/migratedatabase.cc
@@ -425,7 +425,7 @@ bool SignalBackup::migrateDatabase(int from, int to) const
   long long int min = minmax.getValueAs<long long int>(0, "min");
   long long int max = minmax.getValueAs<long long int>(0, "max");
 
-  for (uint i = min; i < max; ++i)
+  for (uint i = min; i <= max; ++i)
   {
     SqliteDB::QueryResults newmmsid;
     if (!d_database.exec("INSERT INTO mms "
@@ -527,17 +527,26 @@ bool SignalBackup::migrateDatabase(int from, int to) const
                          "FROM "
                          "sms "
                          "WHERE "
+#if SQLITE_VERSION_NUMBER < 3035000 // RETURNING was not available prior to 3.35.0
+                         "_id IS ?", i))
+#else
                          "_id IS ? RETURNING _id", i, &newmmsid))
+#endif
     {
       Logger::error("copying sms._id: ", i);
       d_database.exec("ROLLBACK TRANSACTION");
       return false;
     }
 
+#if SQLITE_VERSION_NUMBER < 3035000 // RETURNING was not available prior to 3.35.0
+    if (true)
+    {
+      long long int newestmmsid = d_database.lastId();
+#else
     if (newmmsid.rows())
     {
       long long int newestmmsid = newmmsid.getValueAs<long long int>(0, "_id");
-
+#endif
       // update reactions
       if (!d_database.exec("UPDATE reaction SET message_id = ?, is_mms = 1 WHERE message_id IS ? AND is_mms = 0", {newestmmsid, i}))
       {
```

If you save the above in a file called `returning.patch` in the signalbackup-tools directory, and then apply it, again from inside the directory:

```shell
 $ patch -p1 < returning.patch 
patching file signalbackup/migratedatabase.cc
Hunk #1 succeeded at 426 (offset 1 line).
Hunk #2 succeeded at 528 (offset 1 line).
 $
```
And then recompile, hopefully it will work.

Note there are a few other places in the program where I use a `RETURNING`-clause. I don't think you'll run into them doing the HTML export, but if you would run others functions you might get similar errors. I will try to fix ll the other places too, but have some other bigger changes lined up in a separate branch which I want to get merged first. (this change is already in that other branch as well: [see here](https://github.com/bepaald/signalbackup-tools/commit/62ecd29008a97ee22f3f70ff0224d5c75dfa9672#diff-df13f9c072c179e5566e65a68d849cb7cb3c8bfaceb4207c60bb7eb570907ffd))

Let me know if it works! Thanks!

**Comment by sequc82** [comment]
Hi @bepaald 

Good news! The patch appears to have worked! 

Is the other branch just addressing idiosyncrasies with desktop client?

Thanks again!

**Comment by bepaald** [comment]
Excellent!

The other branch was indeed for dealing with the Desktop clients new encrypted key. The change is mostly bigger, and more involved than others because it requires a new dependency (for Linux) and thus a rewrite of some sections of the README and the compilation scripts, and maybe notifying a few package maintainers. I'm very close though. I've since also been pushing other, unrelated changes to that branch (like the patch you tested), so that's a bit messy. I just need to get the README sorted and merge the branch quickly, hopefully this weekend.
